spring:
  datasource:
    url: jdbc:mysql://${USER_DB_HOST:localhost}:${USER_DB_PORT:33061}/${USER_DB_NAME:userdb}
    username: ${USER_DB_USERNAME:root}
    password: ${USER_DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
